syntax = "proto3";

package pb;

option go_package = "github.com/JawadMM/ecomm/catalog/pb";

service CatalogService {
  rpc PostProduct (PostProductRequest) returns (PostProductResponse);
  rpc GetProduct (GetProductRequest) returns (GetProductResponse);
  rpc GetProducts (GetProductsRequest) returns (GetProductsResponse);
  rpc DecreaseStock (DecreaseStockRequest) returns (DecreaseStockResponse);
  rpc IncreaseStock (IncreaseStockRequest) returns (IncreaseStockResponse);
}

message Product {
  string id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
  uint32 stock = 5;
}

message PostProductRequest {
  string name = 1;
  string description = 2;
  double price = 3;
  uint32 stock = 4;
}

message PostProductResponse {
  Product product = 1;
}

message GetProductRequest {
  string id = 1;
}

message GetProductResponse {
  Product product = 1;
}

message GetProductsRequest {
  uint64 skip = 1;
  uint64 take = 2;
  string query = 3;
  repeated string ids = 4;
}

message GetProductsResponse {
  repeated Product products = 1;
}

message DecreaseStockRequest {
  string product_id = 1;
  uint32 quantity = 2;
}

message DecreaseStockResponse {
  Product product = 1;
}

message IncreaseStockRequest {
  string product_id = 1;
  uint32 quantity = 2;
}

message IncreaseStockResponse {
  Product product = 1;
}
